### ISSUE TITLE
Broken cyrillic output in cmd

### ISSUE THREAD

**Issue by Ratio2** [git-for-windows/git#1087]
In 2.11.1 bug missing
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
```
CMD
```
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git log
```
 - What did you expect to occur after running these commands?
```
second string is cyrillic
эта строка на русском
```
 - What actually happened instead?
```
second string is cyrillic
<D1><8D><D1><82><D0><B0> <D1><81><D1><82><D1><80><D0><BE><D0><BA><D0><B0> <D0><BD><D0><B0> <D1><80><D1><83><D1><81><D1><81><D0><BA><D0><BE><D0><BC>
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
```
https://github.com/Ratio2/git_bug_encoding.git
```

**Comment by fourpastmidnight** [comment]
First, it would be nice to see the exact commands you ran that resulted in that output. Please update your issue with those. Second, I see from your installation that you chose to use MinTYY as the terminal emulator, but also chose to be able to run git from the command prompt. So I'm assuming you're running these commands at a DOS prompt, and not from a Bash shell.

In the meantime, I'll take a few stabs in the dark with the assumptions made above. Unicode is notoriously bad when using the Windows Console Host, which is the "terminal" the Windows Command Prompt (i.e. DOS) uses.. Make sure the code page for the command prompt is 65001. The output you show above, however, looks like it may have come from a `git log` or `git show` command. In that case, it could be the `less` pager settings. In your command prompt, do you have a `LANG` environment variable? If so, what's its value?

Without more information, it's hard to help you.

**Comment by Ratio2** [comment]
@fourpastmidnight I use simple cmd.exe, not bash cmd, install option no meaning. LANG env var not set.
In Far Manager problem also exists.
Seems problem in pager, becuase "git --no-pager log" output propper.
In my previous git version 2.11.1 all work in the same environment.

**Comment by Ratio2** [comment]
@fourpastmidnight set LANG=en_US.UTF-8 fixed problem, but why? cmd.exe don't use utf8.
Because less.exe expect input in LANG encoding and git always output in utf8?

**Comment by Ratio2** [comment]
@fourpastmidnight After some investigation i found that git set different env for pager
2.11.1 LC_ALL=C.UTF-8
2.12.0 LC_CTYPE=C

**Comment by PhilipOakley** [comment]
Have a look at the various issues that cover 'ascii' which affect V2.11.x such as #1053 #945 #1036. (check for how your symptom is shown)

I believe all those issues have been fixed in v2.12.x  but do check that you have got the appropriate encoding setting fixes that some of those threads mentioned.

Getting the encodings right in the different parts of the infrastructure is tricky - an update to V2.12 may be the reasonable resolution.

**Comment by zoidbergthepopularone** [comment]
I am having exactly the same problem. Incidentally, this problem seems to keep recurring - it was present in 2.11.0, got fixed in 2.11.1-prerelease1, reappeared in 2.12.0. I even made sure to run all of these versions side by side and try git-log from all these versions from a single CMD.EXE prompt, from the same window, against the same sample repository (a single commit with a message "ěščřžýáíé"). v2.11.1-prerelease1 will display a proper output, v2.12.0 and v2.11.1 will display a garble output with hexacodes instead of the characters.

**Comment by zoidbergthepopularone** [comment]
![git-2 11 1-pre1](https://cloud.githubusercontent.com/assets/16563159/23762053/2da8d166-04f5-11e7-9112-0fb74c3bef85.png)
![git-2 12 0](https://cloud.githubusercontent.com/assets/16563159/23762054/2daf70c0-04f5-11e7-9575-7b69951a6273.png)

**git ll** is defined as **git log --oneline --graph --all --decorate**. No other special setup that I know of. The console is unicode and uses a unicode prompt.

**Comment by fourpastmidnight** [comment]
IIRC, if `LANG` is not set, and neither of the `LC_*` environment variables are set, `less` defaults to C locale, which is more or less the ASCII code page--and I believe specifically the range of 0x00-0x7F (0 - 127). And so yes, git outputs UTF-8, but `less` converts its input to basically ASCII, and you get garbled output at the end. **Oh, I see that you later said `LC_CTYPE` was set to `C`. That explains some more.**

So, if no `LC_*` variables are set, you get C locale. Otherwise, the `LC_*` variables are examined and used. Finally, if `LANG` is set, that value overrides any `LC_*` values. That should explain why setting `LANG` to `en_us.UTF-8` resolved your issue.

The key here is recognizing that there is a pipleine, and any input/output encoding mismatch may result in display issues. With `less` usually appearing at the end of the pipeline, it's important to ensure `less` is configured correctly, particularly the locale for it's output.

**Comment by fourpastmidnight** [comment]
@Ratio2 Hmm, good observation about the differences in `LC_*` environment variables set between 2.11 and 2.12.

@dscho 
Is there some sort of "regression test" we can put in place for releases to ensure each release has a consistent setting for the locale environment variables? I.e. A safe default that we ship--and perhaps documented in the README?

**Comment by Ratio2** [comment]
@fourpastmidnight I think that locale must be always forced to utf-8 (LC_CTYPE=C.UTF-8) because git output always in utf-8:
https://github.com/git-for-windows/git/commit/1869af5c4f7d424a3b2771645a26f086b3928dff
> Finally, if LANG is set, that value overrides any LC_* values.
May be opposite? https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html

**Comment by Ratio2** [comment]
@fourpastmidnight @PhilipOakley @dscho @zoidbergthepopularone 
After some investigation:
1. Problem occured because msys runtime not strip quotes when convert GetCommandLine() to argv. In msys2-runtime package if glob failed we stay with quotes.
2. Problem occured only with C and C.UTF-8 locales
3. Problem fixed with en_US.UTF-8, en_US.UTF8, en_US.utf-8, en_US.utf8, C.UTF-8, C.UTF8, C.utf-8, C.utf8 locales
4. locale -a: C.utf8, en_US.utf8
5. Very strange en_US.UTF-8 work but C.UTF-8 not

I think we can change https://github.com/git-for-windows/git/commit/1869af5c4f7d424a3b2771645a26f086b3928dff locale to C.utf8:
1. Fixed this bug
2. List under locale -a
3. No regression to https://github.com/git-for-windows/git/issues/1036

**Comment by dungdm93** [comment]
I got the same issue:
![git 2 12](https://cloud.githubusercontent.com/assets/6848311/23936936/68d58464-0987-11e7-89c5-4dfe9a511fc4.png)
![git 2 9](https://cloud.githubusercontent.com/assets/6848311/23936939/6ac55948-0987-11e7-87fd-d9953f181967.png)

**Comment by thomazpadilha** [comment]
I'm also having the same problem on log with accented words (brazilian portuguese).

As @Ratio2 commented, git log shows output with weird encoding:
```
commit e0c819c711b4de37d9738410c8d69678969d699a
Merge: ebcb8f2 9bb33f4
Author: Thomaz Moura <thomaz.moura@autotrac.com.br>
Date:   Thu Mar 9 17:23:47 2017 -0300

    PR 29: Altera<C3><A7><C3><A3>o do tempo de sess<C3><A3>o para 1 hora

     - Altera<C3><A7><C3><A3>o do tempo de sess<C3><A3>o para 1 hora

    Related work items: #20612
```
However, with git --no-pager the output works correctly:
```
commit e0c819c711b4de37d9738410c8d69678969d699a
Merge: ebcb8f2 9bb33f4
Author: Thomaz Moura <thomaz.moura@autotrac.com.br>
Date:   Thu Mar 9 17:23:47 2017 -0300

    PR 29: Alteração do tempo de sessão para 1 hora

     - Alteração do tempo de sessão para 1 hora

    Related work items: #20612
```
I'm using powershell here. I've tried the set `LANG=en_US.UTF-8` solution and it seems to have worked for cmd and git bash, but not with powershell.

**Comment by sobolevsv** [comment]
same problem
"git --no-pager log" outputs correctly, but
"git log" does not

**Comment by bllngr** [comment]
We're still having this issue on 2.21 and 2.22 with any non-ASCII characters:

```cmd
c:\git-issue-1087> git init
c:\git-issue-1087> git commit -m "Tést" --allow-empty
c:\git-issue-1087> git log --oneline
941968f (HEAD -> master) T<C3><A9>st
c:\git-issue-1087> git --no-pager log --oneline
941968f (HEAD -> master) Tést
```

We'd rather not have to manually set ``LC_ALL`` on all developer machines. Shouldn't git/less handle the normalization to the current shell's encoding?

**Comment by SetTrend** [comment]
Just a thought: At the eve of PowerShell and Unicode becoming a standard nowadays ... Does it still make sense to use an obsolete ASCII focussed tool like `less`?

I tend to believe it'd rather make sense to utilize Windows _native_ pager tools.

Or wouldn't it be even more appropriate to omit intrinsic usage of pager tools at all and leave paging to being entered manually by using native PowerShell/Command Line piping, e.g. `git log | more`?
