### ISSUE TITLE
Local system administator environment variables.

### ISSUE THREAD

**Issue by dannce** [git-for-windows/git#179]
Git can't handle the SSH system environment variables well when it is run as the local system administrator. For example when using PStools ( PsExec.exe -i -s cmd.exe ) and try to run git ls-remote ssh://<url> I get a message: could not create directory '/home/system/.ssh'. This is because the variable 'home' does not exist. Of course I could set the system envirionment variable of 'home', but then the ssh directory will not point to the default ssh directory, which is: C:\Windows\System32\config\systemprofile\.ssh.

**Comment by dscho** [comment]
For the future: you might want to consider making it as easy as possible for others to recreate the problem on their side. I assume you are talking about https://technet.microsoft.com/en-us/sysinternals/bb897553.aspx, i.e. Microsoft SysInternals' PsExec 2.11. Of course, this is an assumption, and I would have preferred to find the exact information in the bug report.

Now to the problem: There must be more going on here, as not only the `HOME` environment variable is looked at, but also `HOMEDRIVE\HOMEPATH`, and if that does not exist, `USERPROFILE`. If all of those fail to point at your current user's home directory, you are expected to be an administrator who knows what they are doing, i.e. set the `HOME` directory to the appropriate directory yourself: SSH *requires* a home directory to work.

**Comment by dscho** [comment]
I assume that this ticket was addressed by my explanation why `HOME` must be set manually if MSys2 cannot figure out the current user's home directory.

**Comment by dannce** [comment]
I'm sorry about my limited bug report, it is unclear. I'll expand on it.

How to recreate:
 1. Download and extract PsTools from http://download.sysinternals.com/Files/PsTools.zip
 2. Open a normal cmd shell (as adminstrator) and run: c:\>PsTools/PsExec.exe -i -s cmd.exe
 3. Run git ls-remote ssh://<your fav git repo>

Note: the problem isn't that git can't login, the problem is that git can't update the known_hosts file in the ssh-directory.

I do disagree with closing the issue, because:
 1. my environment variables are set. Especially USERPROFILE is set to `C:\Windows\System32\config\systemprofile.ssh`
 2. git 1.9.5 for windows uses these variables correctly
 3. I get the error: `Could not create directory '/home/SYSTEM/.ssh' `. The path `/home/SYSTEM/.ssh` is totally unexpected in Windows.

**Comment by dscho** [comment]
When you start `Git Bash`, in which directory does it start? (`pwd -W` is your friend).

**Comment by dannce** [comment]
If I run Git bash or cmd.exe as the local system administrator it starts at directory C:\Windows\system32.

Even if the cmd would start at C:\Windows\System32\config\systemprofile, which is both HOME and USERPROFILE of the system administrator, I still don't understand why Git would try to access the folder /home/SYSTEM/.ssh since the .ssh directory is /HOME/.ssh.
