### ISSUE TITLE
git-cmd.exe does not run first passed command parameter

### ISSUE THREAD

**Issue by tuspet** [git-for-windows/git#2039]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
 - Git version: 2.20.0
 - Our team uses the 32-bit Portable Git version
 - Machine: Win10 1803 64 bit
### Details
Our software runs a git-cmd command to display the actual git home directory:
```
git-cmd.exe "echo %HOME% && exit"
```
This command answered with the correct path in 2.19.2 and earlier versions but returns nothing in 2.20.0.
After checking this problem deeply we found that now the 2.20.0 git-cmd.exe does not execute the first passed parameter. See the following easy command with multiple passed commands:
```
git-cmd.exe "echo 11 && echo 22 && echo 33 && exit"
```
The expected result is:
```
11
22
33
```
But 2.20.0 displays only:
```
22
33 
```

**Comment by PhilipOakley** [comment]
Could you confirm the two path environment strings you have in the two versions.

Ensuring the right variant of the .exe files is run can be a big problem (especially given the issue of catching Ctrl-C in the different environments). I'm not an expert in that area but  there have been on-going issues between the different interpretations about how to handle the different OS paradigms....

**Comment by tuspet** [comment]
Hi,
This problem is not connected to the environment.
The real problem is the following:
Although you can give a command-list to the git-cmd.exe passed as one long parameter (separated by the && characters) the newer git versions (2.20.0 and 2.10.1) forget to launch the first command in the list.
(Seemingly git-cmd starts to launch the passed commands from a wrong index.)
See the following screenshot as a clear reproduction of the issue:
![gitcmd_issue_2039_with_example](https://user-images.githubusercontent.com/5808658/51831662-eae7ca80-22f2-11e9-9b34-6c66a09e04e4.PNG)

**Comment by dscho** [comment]
I can confirm.

**Comment by dscho** [comment]
A new [snapshot](https://wingit.blob.core.windows.net/files/index.html) is available that should fix this issue. Could I ask y'all to please test?

**Comment by tuspet** [comment]
Hi,
I downloaded the latest snapshot: Portable Git (self-extracting .7z archive):  **32-bit**.
**Tue, 29 Jan 2019 20:05:21 +0100 (commit 9f16cdd421)**

For me it seems that the problem is not yet fixed.

I hope I downloaded a correct package as it seems that the issue is still reproducible:

![for github issue 2039_still not working](https://user-images.githubusercontent.com/5808658/52414521-dcfd2b00-2ae4-11e9-86d7-cdf9b0943d5f.PNG)

Unfortunately I found still (**_an additional_**) problem with the parameter processing. See following picture:

![for github issue 2039_additional problem](https://user-images.githubusercontent.com/5808658/52414807-9825c400-2ae5-11e9-9ff1-71d48c2215b5.PNG)

1. Open a normal cmd.exe and go to the extracted git folder.
2. Launch the **_git-cmd.exe "echo Apple && echo Banana"_** command (no exit command at the end!)
3. As we are inside the git command line now, try to launch any git command like git --version. None of them are working.

If you think that this second problem is not connected to this parameter problem then I can open a new issue with it.

**Comment by dscho** [comment]
@tuspet please re-test with v2.21.0-rc2.

**Comment by tuspet** [comment]
Hi,

Thank you very much. Really great! It seems that the git-cmd.exe works now as expected.
![image](https://user-images.githubusercontent.com/5808658/53254363-82a6c180-36c3-11e9-9af3-35085ce047f5.png)
The result is okay when we are in the simple cmd.exe, and when we are inside the git-cmd.exe.
See the attached picture. Thanks again!

**Comment by dscho** [comment]
@tuspet thanks for testing!
