### ISSUE TITLE
Unicode filenames do not display correctly in 2.27.0 in status command

### ISSUE THREAD

**Issue by lourdas** [git-for-windows/git#2734]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.836]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Νο.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git status
```
 - What did you expect to occur after running these commands?

See the filename as it is.

 - What actually happened instead?

ASCII characters appear in place of the unicode filename characters.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No.

Tested with a filename written in Greek (`Γεια!.txt`) with content both in Greek and English. The content is displayed correctly (`git diff`), while the status command does not display the filename correctly (`git status`).

Attached screenshot of Git 2.26.2:
![git-2 26 2](https://user-images.githubusercontent.com/397916/86509157-92bdcd80-bdee-11ea-87c5-c5fa0116bf03.png)

Attached screenshot of Git 2.27.0:
![git-2 27 0](https://user-images.githubusercontent.com/397916/86509160-9b160880-bdee-11ea-8918-9785d7b392b2.png)

**Comment by dscho** [comment]
Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html). If the problem persists, do try to craft a [Minimal, Complete & Verifiable Example](https://stackoverflow.com/help/minimal-reproducible-example). It will dramatically increase your chances to receive helpful assistance.

**Comment by lourdas** [comment]
Tested the latest snapshot. Same status:

![git-snapshot](https://user-images.githubusercontent.com/397916/86622874-4c709600-bfc9-11ea-94ac-b7894f6e402b.png)

To test it, create a empty directory with a new repository, create a file with a non-latin name and add it to stage. Run `git status` and you will get this behaviour.

**Comment by dscho** [comment]
For me, it does this: 
![image](https://user-images.githubusercontent.com/127790/86918475-12b5a180-c127-11ea-9938-5c4ec2504ce6.png)

This is consistent with how the file name is presented in my Linux setup.

Maybe you are bitten by the bug (fixed in the meantime) where Pseudo Console support was not properly re-disabled during a reinstall?

**Comment by lourdas** [comment]
The screenshot above looks correct if I change `core.quotePath` to true, but as you understand hexadecimal values do not mean something to the human eye. Just tried the latest snapshot `2.27.0.windows.1.18.g51f9af323b.20200707200701` and still the same behavior. What else can I try?

**Comment by dpap** [comment]
git 2.27.1 doesn't reproduce greek characters correctly with the mintty console.

I tried changing mintty options -> text -> to utf-8 , iso8859-7, cp737, cp1253 but nothing works

also a nodejs "pm2 list" command produces garbed output

**Comment by lourdas** [comment]
Could this be some kind of MinTTY issue?

**Comment by lourdas** [comment]
Actually, I tried git-cmd.exe which I suppose uses the classic command console from Windows and the filename is displayed correctly:

![git-cmd](https://user-images.githubusercontent.com/397916/87507363-f7dab400-c675-11ea-9c96-6dbcbac6bfe3.png)

This is from the latest snapshot (dated Jul 7th).

**Comment by jfcherng** [comment]
I think it's the same issue with mine https://github.com/git-for-windows/git/issues/2648.

**Comment by lourdas** [comment]
Similar to #2793.

**Comment by jfcherng** [comment]
Fwiw, I am using [this](https://github.com/msys2/MSYS2-packages/issues/2012#issuecomment-657081801) workaround.

**Comment by dscho** [comment]
> Fwiw, I am using [this](https://github.com/msys2/MSYS2-packages/issues/2012#issuecomment-657081801) workaround.

@jfcherng a better work-around would be to run `cmd //c chcp 65001`, but I think we have a good grasp on https://github.com/msys2/MSYS2-packages/issues/1974 and once that is resolved, this here bug will be fixed, too.

**Comment by jfcherng** [comment]
> > Fwiw, I am using [this](https://github.com/msys2/MSYS2-packages/issues/2012#issuecomment-657081801) workaround.
> 
> @jfcherng a better work-around would be to run `cmd //c chcp 65001`, but I think we have a good grasp on [msys2/MSYS2-packages#1974](https://github.com/msys2/MSYS2-packages/issues/1974) and once that is resolved, this here bug will be fixed, too.

Thanks for this information! I will try tomorrow when I go working :+1:

**Comment by dscho** [comment]
Could you re-test with the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html), please?

**Comment by lourdas** [comment]
Yes, it works fine here.

![1](https://user-images.githubusercontent.com/397916/94137217-c00a9c80-fe6e-11ea-97b5-6f9c702e2a04.png)

**Comment by dpap** [comment]
Using portable version portableGit-prerelease-2.28.0.windows.1-51-g87c86a26de-20200923135803-64.

Seems to be working like version 2.25.1 ie. directory listing seem ok. Code page (chcp.com) on 2.25.1 is 737 while on new version it is 65001.  git status shows unicde codes but that's ok

Portable version is a bit slow to respond but I have 2.25.1 installed too and I don't want to remove before new version released

**Comment by dscho** [comment]
Thank you, all!
