### ISSUE TITLE
git-subtree installation is broken

### ISSUE THREAD

**Issue by devhawk** [git-for-windows/git#3260]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.985]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

<using PortableGit, no install-options>
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Only seems to happen with Portable git. invoking subtree when git is installed via winget on this machine works fine

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git subtree
```
 - What did you expect to occur after running these commands?

help content of git subtree command

 - What actually happened instead?

```
It looks like either your git installation or your
git-subtree installation is broken.

Tips:
 - If `git --exec-path` does not print the correct path to
   your git install directory, then set the GIT_EXEC_PATH
   environment variable to the correct directory.
 - Make sure that your `git-core\git-subtree` file is either in your
   PATH or in your git exec path (`C:/Users/harry/Downloads/PortableGit/mingw64/libexec/git-core`).
 - You should run git-subtree as `git core\git-subtree`,
   not as `git-core\git-subtree`.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

**Comment by devhawk** [comment]
Note, winget is installing 2.31.1, where subtree appears to work. when I installed the non-portable version of 2.32.0, git subtree was still broken.

```
$ git --version --build-options
git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

```
$ type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

**Comment by dscho** [comment]
Could you maybe bisect through the [snapshots](https://wingit.blob.core.windows.net/files/index.html) (both v2.32.0 and v2.31.1 are in there)?

I would love to assist, but I am somewhat worn out by a lengthy bug hunt today.

**Comment by rimrul** [comment]
> You should run git-subtree as `git core\git-subtree`,
   not as `git-core\git-subtree`.

That's interesting. That's probably supposed to say something more like

> You should run git-subtree as `git subtree`,
   not as `git-subtree`.

Did we change something about how we call scripted commands? Specifically regarding working directory?

**Comment by dscho** [comment]
If that were the case, other dashed command should be affected, too (e.g. `git-remote-https`.

I vaguely remember that @avarb played in `contrib/subtree`, though...

**Comment by rimrul** [comment]
I think the person who did most things in contrib/subtree between 2.31 and 2.32 was @LukeShu, though. Including [the commit that introduced our error message] (https://github.com/git/git/commit/22d550749361ff2a480bc4263ae21919368851ed)

**Comment by rimrul** [comment]
And it seems to be the

```sh
test "${PATH#"${GIT_EXEC_PATH}:"}" = "$PATH"
```

in line 8 of `git-subtree` that causes it to error out.

**Comment by rimrul** [comment]
That commit message says 

>After being executed by `git`, the git exec path should be the very first entry in PATH, so it shouldn't matter.

yet it errors out, if that is actually the case. I think that `=` was supposed to be  `!=`.

**Comment by rimrul** [comment]
I'll try to check if these issues also appear on linux tomorrow. I think I'll encounter the same issues on arch's official git package. I'll then submit fixes to the appropriate places.

**Comment by dscho** [comment]
The culprit is 22d550749361ff2a480bc4263ae21919368851ed. And it probably only breaks on Windows, and it breaks _hard_ here.

The reason is that it asks `"${PATH#"${GIT_EXEC_PATH:"}"` to be different from "$PATH", which means that it expects `PATH` to start with `$GIT_EXEC_PATH:`.

The problem is that `GIT_EXEC_PATH` is a Windows-style path, i.e. `C:/Program Files/Git/mingw64/libexec/git-core`. And `PATH` starts with `/mingw64/libexec/git-core:`, which is the Unix-style path.

**Comment by rimrul** [comment]
You're forgetting MSYS path conversion.

When I add two echo lines to `git-subtree`, one for each side of the test and call `git subtree`, they both start with `/mingw64/libexec/git-core:`.

**Comment by dscho** [comment]
@devhawk could I trouble you to download the installer from https://github.com/git-for-windows/git/actions/runs/922160854 to verify that the fix I provided in https://github.com/git-for-windows/git/pull/3264 works for you?

**Comment by dscho** [comment]
> 
> 
> Sorry for the noise, I missunderstood both you and the script...

No worries at all, your help was invaluable. I would not have been able to investigate, and the fix would not have come around this quickly.

**Comment by devhawk** [comment]
> @devhawk could I trouble you to download the installer from https://github.com/git-for-windows/git/actions/runs/922160854 to verify that the fix I provided in #3264 works for you?

I downloaded the portable version and was able to run git subtree on my windows box without issue. Thanks @dscho!

**Comment by LukeShu** [comment]
> > You should run git-subtree as `git core\git-subtree`,
> > not as `git-core\git-subtree`.
> 
> That's interesting. That's probably supposed to say something more like
> 
> > You should run git-subtree as `git subtree`,
> > not as `git-subtree`.

Indeed!  The error message is borked because when it's deciding what to print it assumes that the directory separator is forward-slash `/`, not Windows' back-slash `\`.

**Comment by LukeShu** [comment]
> I'll try to check if these issues also appear on linux tomorrow. I think I'll encounter the same issues on arch's official git package. I'll then submit fixes to the appropriate places.

I'm using `git subtree` a few changes ahead of what's landed in git.git, but: I'm on Parabola, which is downstream of Arch, so Arch is the platform that I'd _least_ expect to see issues on.

**Comment by rimrul** [comment]
>I'm on Parabola, which is downstream of Arch, so Arch is the platform that I'd _least_ expect to see issues on.

Yes, that comment was based on my poor understanding of the issue.

**Comment by CaseGuide** [comment]
FYI for those encountering the *git-subtree installation is broken* issue and landing here via google after getting this error message:

# It looks like either your git installation or your git-subtree installation is broken.

```
It looks like either your git installation or your git-subtree installation is broken.

Tips:
 - If `git --exec-path` does not print the correct path to
   your git install directory, then set the GIT_EXEC_PATH
   environment variable to the correct directory.
 - Make sure that your `git-core\git-subtree` file is either in your
   PATH or in your git exec path (`C:/Program Files/Git/mingw64/libexec/git-core`).
 - You should run git-subtree as `git core\git-subtree`,
   not as `git-core\git-subtree`.
```

It appears the git subtree installation is broken issue is with Git for Windows.

I was able to download an older version from: https://github.com/git-for-windows/git/releases/download/v2.31.0.windows.1/Git-2.31.0-64-bit.exe

This fixed the issue for me while we await a fix.

**Comment by dscho** [comment]
@CaseGuide please avoid suggesting to downgrade when we worked so hard on a fix. Point people to the installer artifact of https://github.com/git-for-windows/git/actions/runs/922160854 instead. That's much, much better advice.

**Comment by tplunket** [comment]
@dscho I just got hit by this in a weird spot where I basically have to stop work. This was fixed two weeks ago, about four days after the previous release; maybe the artifacts are great but it's not clear what those will do to the normal update process in git-for-windows. How long until a new release appears either on the releases page or in `update-git-for-windows` ? (Certainly this is something that would warrant a 2.32.1 release?)

**Comment by bertiewooster** [comment]
Hi @dscho I tried to download installer-x86_64 but got this error in WinZip:
Cannot open file 'installer-x86_64.zip'. It does not appear to be a valid archive.
It works fine on a Mac, but of course this is for Windows.

**Comment by dscho** [comment]
> This was fixed two weeks ago

The fix is still under discussion on the Git mailing list: https://github.com/gitgitgadget/git/pull/978. It has not even been accepted into Git's `next` branch, therefore it would be really premature to integrate it into Git for Windows' `main` _already_.

> maybe the artifacts are great but it's not clear what those will do to the normal update process

The upgrade process should be the exact same. No downgrades should be suggested, but once a new version is available, it should be offered for installation.

> Edit: The .zip file worked when I tried downloading it again.

Yes, I saw that from time to time that downloads "succeeded" even if they were incomplete. I think it is an Amazon S3 issue, but I can't know for certain.

**Comment by builder-main** [comment]
Hi, Thanks for the fix, yet I tried to install it but I still have the issue.
```
$ git --version
git version 2.32.0.windows.1.8.g262eaa2f4f.20210614151600

$ git subtree
It looks like either your git installation or your
git-subtree installation is broken.

Tips:
 - If `git --exec-path` does not print the correct path to
   your git install directory, then set the GIT_EXEC_PATH
   environment variable to the correct directory.
 - Make sure that your `git-core\git-subtree` file is either in your
   PATH or in your git exec path (`C:/Program Files/Git/mingw64/libexec/git-core`).
 - You should run git-subtree as `git core\git-subtree`,
   not as `git-core\git-subtree`.
```

**Comment by rimrul** [comment]
> built from commit: 262eaa2f4f...

That's quite an odd commit. And I don't think it has this fix.
Could you try the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html)?

**Comment by dscho** [comment]
> > built from commit: [262eaa2](https://github.com/git-for-windows/git/commit/262eaa2f4f40e37904d6413d34cf7583dd222e45)...
> 
> That's quite an odd commit. And I don't think it has this fix.

Indeed. It looks like this Git version was indeed built from a revision that does not have the fix: https://github.com/git-for-windows/git/compare/262eaa2f4f40e37904d6413d34cf7583dd222e45...5f2d9434b4ebb66131ea2fb9fbb62d6338af1294 (the fix is in 5f2d9434b4ebb66131ea2fb9fbb62d6338af1294).
