### ISSUE TITLE
Incorrect cherry-pick conflict message encoding

### ISSUE THREAD

**Issue by yaras** [git-for-windows/git#664]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

 Git-2.7.1.2-64-bit.exe

```sh
$ git --version
git version 2.7.1.windows.2
```

 - Which version of Windows are you running? 32-bit or 64-bit?

 Windows 10 Home, 64 bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 defaults

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 MinTTY

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init .
echo "test" > test
git add . && git commit -m 'Initial'

git checkout -b development
echo "a" >> test
git add . && git commit -m 'Change on devel (ęółąśłżźćń)'

git checkout master
echo "b" >> test
git add . && git commit -m 'Change on master'
```

After above steps my repository looks like:

```
$ git log --graph --oneline --branches --decorate
* d1cd79c (HEAD -> master) Change on master
| * ab514a8 (development) Change on devel (ęółąśłżźćń)
|/
* 698a591 Initial
```

Then I cherry-pick “Change on devel (…)” which produces expected conflict:

```
$ git cherry-pick development
error: could not apply ab514a8... Change on devel (ęółąśłżźćń)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

$ git status
On branch master
You are currently cherry-picking commit ab514a8.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:   test

no changes added to commit (use "git add" and/or "git commit -a")
```

and creates a file `.git/MERGE_MSG` which contains message with valid encoding:

```
$ cat .git/MERGE_MSG
Change on devel (ęółąśłżźćń)

# Conflicts:
#       test
```

But, when  I run `git gui` initial commit message gets invalid encoding (which is reflected in `GITGUI_MSG` file):

```
$ git gui

$ cat .git/GITGUI_MSG
Change on devel (Ä™ĂłĹ‚Ä…Ĺ›Ĺ‚ĹĽĹşÄ‡Ĺ„)

# Conflicts:
#       test
```

 - What did you expect to occur after running these commands?

I expect valid encoding in `git gui` window and in `GITGUI_MSG` file.

 - What actually happened instead?

 Message in commit prompt in `git gui` has invalid encoding.

### Fix proposal

I think that the problem is in git-gui load_message function and this is my fix proposal:

```
diff --git a/git-gui/git-gui.sh b/git-gui/git-gui.sh
index 0290a45..73c653a 100755
--- a/git-gui/git-gui.sh
+++ b/git-gui/git-gui.sh
@@ -1472,7 +1472,7 @@ proc rescan {after {honor_trustmtime 1}} {
                 if {[string match amend* $commit_type]} {
                 } elseif {[load_message GITGUI_MSG utf-8]} {
                 } elseif {[run_prepare_commit_msg_hook]} {
-                } elseif {[load_message MERGE_MSG]} {
+                } elseif {[load_message MERGE_MSG utf-8]} {
                 } elseif {[load_message SQUASH_MSG]} {
                 }
                 $ui_comm edit reset
```

before I create a pull-request I’d like to consult whether it is a good way of fixing it and whether I should also add `utf-8` to loading SQUASH_MSG.

Next week I'm going to test this fix and if it solves the problem I'll create a Pull Request.

I'd like to write some tests, but I have no idea how to simulate run of `git gui`. Any suggestions?

**Comment by PhilipOakley** [comment]
This sounds like a solid improvement to be sent upstream to the Git List <git@vger.kernel.org> and the two maintainers, Junio C Hamano <gitster@pobox.com> (Git) and Pat Thoyts <patthoyts@users.sourceforge.net> (Git Gui) - The git gui has it's own maintainer -Pat's last update for Junio (AFAICT) is http://thread.gmane.org/gmane.comp.version-control.git/267419. 

SHould the other messages recieve the same treatment? The SQUASH_MSG may have the same issue.

**Comment by dscho** [comment]
Yes, I agree that the patch should fix this, and that SQUASH_MSG should be treated the same. BTW `git gui` is maintained only by @patthoyts, not by @gitster.

> I'd like to write some tests, but I have no idea how to simulate run of git gui.

Alas, no. I found myself wishing for the same a lot of times already. Maybe write to [the Git mailing list](mailto:git@vger.kernel.org) and ask for guidance regarding automated regression tests for `git gui`?

**Comment by PhilipOakley** [comment]
> BTW  git gui  is maintained only by @patthoyts, not by @gitster.

Sorry for the confusion. I was trying (ineffectively) to convey the flow between the different repos. Often the changes are discussed on the Git List and then formally picked up by @patthoyts; then @gitster picks them up from him.

**Comment by yaras** [comment]
### Git squash test

I managed to reproduce bug for `SQUASH_MSG` and prepared test case:

```sh
git init .
echo 'a' > a && git add . && git commit -m 'added A'
git checkout -b devel
echo 'b' > b && git add . && git commit -m 'added B (ęóąśłżźćń)'
echo 'bbb' >> b && git add . && git commit -m 'changed B (żźćńąśłóę)'
git checkout master
git merge --squash devel
```

after running above then on `git gui` message prompt I see invalid encoding, so this is the same problem.

### Send patch upstream to git

> This sounds like a solid improvement to be sent upstream to the Git List git@vger.kernel.org and the two maintainers, Junio C Hamano gitster@pobox.com (Git) and Pat Thoyts patthoyts@users.sourceforge.net (Git Gui) - The git gui has it's own maintainer
> [...]
> BTW git gui is maintained only by @patthoyts, not by @gitster.

I'll contact @patthoyts via mailing list.

>  Maybe write to the Git mailing list and ask for guidance regarding automated regression tests for git gui?

I'll do.

### Testing fix

I've rebuild _git_ containing my patch, but unfortunatelly it did not fix the issue, the encoding was still invalid.

After short investigation I came to conclusion that it is not loading `MERGE_MSG`/`SQUASH_MSG` issue, because executions doesn't reach that point, it is terminated on `run_prepare_commit_msg_hook`. 

So the bug is in `run_prepare_commit_msg_hook`. This procedure takes `MERGE_MSG` and puts it to `PREPARE_COMMIT_MSG`, but looses encoding in a meantime. After initializing `fd_mm` and `fd_sq` there should be `fconfigure` setting encoding:

```
diff --git a/git-gui/git-gui.sh b/git-gui/git-gui.sh
index 1834f00..5771973 100755
--- a/git-gui/git-gui.sh
+++ b/git-gui/git-gui.sh
@@ -1599,11 +1599,13 @@ proc run_prepare_commit_msg_hook {} {
        if {[file isfile [gitdir MERGE_MSG]]} {
                set pcm_source "merge"
                set fd_mm [open [gitdir MERGE_MSG] r]
+               fconfigure $fd_mm -encoding utf-8
                puts -nonewline $fd_pcm [read $fd_mm]
                close $fd_mm
        } elseif {[file isfile [gitdir SQUASH_MSG]]} {
                set pcm_source "squash"
                set fd_sm [open [gitdir SQUASH_MSG] r]
+               fconfigure $fd_sm -encoding utf-8
                puts -nonewline $fd_pcm [read $fd_sm]
                close $fd_sm
        } else {
```

After above fix all my cases seem to pass.
